# Generated by Django 3.1.3 on 2020-12-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_Name',
            new_name='name',
        ),
    ]
