# Generated by Django 3.1.3 on 2020-12-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201203_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='course', max_length=200),
            preserve_default=False,
        ),
    ]
