# Generated by Django 3.1.3 on 2021-03-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
