# Generated by Django 3.1.3 on 2021-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210311_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('stream_key', models.CharField(max_length=200)),
                ('stream_url', models.CharField(max_length=200)),
                ('live', models.BooleanField()),
            ],
        ),
    ]
