# Generated by Django 3.1.3 on 2021-03-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
