# Generated by Django 3.1.3 on 2021-06-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
    ]
