# Generated by Django 3.1.3 on 2021-06-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20210612_2040'),
        ('accounts', '0010_remove_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ForeignKey(default='OtO82ntxj5s', on_delete=django.db.models.deletion.CASCADE, to='root.video'),
            preserve_default=False,
        ),
    ]
