# Generated by Django 3.1.3 on 2021-06-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210615_1857'),
        ('accounts', '0012_remove_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ForeignKey(default='ok', on_delete=django.db.models.deletion.CASCADE, to='root.video'),
            preserve_default=False,
        ),
    ]
