# Generated by Django 3.1.3 on 2021-06-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210615_1857'),
        ('accounts', '0013_course_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.video'),
        ),
    ]
