# Generated by Django 3.1.3 on 2021-06-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210615_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
    ]
