# Generated by Django 3.1.3 on 2021-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_url',
            new_name='stream_code',
        ),
    ]
