# Generated by Django 3.1.3 on 2021-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20210503_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('stream_key', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
