# Generated by Django 3.1.3 on 2021-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20210615_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='stream_key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
