# Generated by Django 3.1.3 on 2021-06-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course_name',
        ),
    ]
