# Generated by Django 3.1.3 on 2021-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_remove_video_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_code',
            field=models.CharField(default='OtO82ntxj5s', max_length=200),
            preserve_default=False,
        ),
    ]
