# Generated by Django 3.1.3 on 2021-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_video_video_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='save_stream',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
